// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int	N = Integer.parseInt(args[0]);

		int i = 0;
		int lessThanHalf = 0;
		int moreThanHalf = 0;
		
		while (i < N) {
			if (Math.random() <= 0.5) {
			lessThanHalf++;
			} else {
			moreThanHalf++;
			}
			i++;

			}

		System.out.println("> 0.5: " + moreThanHalf);
		System.out.println("<= 0.5: " + lessThanHalf);
		if (lessThanHalf!=0) {
			System.out.println("Ratio: " + (double)moreThanHalf / (double)lessThanHalf);

		}

		}
		
	}

